### ISSUE TITLE
Catfish keeps searching, stuck into a loop.

### ISSUE THREAD

**Issue by stepnjump** [chrisbaldauf/catfish#1]
Hi guys,

I used to use catfish and it as working great under Linux Mint 17.2 before. I recently changed for 17.3 and now, the version 1.2.2 that I installed from the official repositories doesn't seem to work.
Symptoms: It searches and searches and searches

Currently system:

Linux HP-Compaq-6005-Pro 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Distributor ID:	LinuxMint
Description:	Linux Mint 17.3 Rosa
Release:	17.3
Codename:	rosa

Desktop: Cinnamon

When I run from terminal, I get following error:
** (catfish.py:16290): CRITICAL **: atk_object_set_description: assertion 'ATK_IS_OBJECT (accessible)' failed

Thank you

**Comment by chrisbaldauf** [comment]
Hi @stepnjump,

I think you might have the wrong catfish project. This was a very short-lived Ruby project and the debugging output that you've posted lists catfish.py.

I'm going to close this, but if I've done so in error, please just let me know.

**Comment by stepnjump** [comment]
Hi Chris,

I installed it through the linux mint main reposity for Linux Mint Rosa and Trusty for base repository via the add-get install command line. When will the new version 1.4.1 be available through the apt-get install ?
I even installed the version 1.4.1 via the synaptic but now when I invoke it, it doesn't even do anything. 
From the terminal, I get:

 [job #0] /usr/bin $ ./catfish
Traceback (most recent call last):
  File "./catfish", line 42, in <module>
    catfish.main()
  File "/usr/lib/python3/dist-packages/catfish/__init__.py", line 74, in main
    window = CatfishWindow.CatfishWindow()
  File "/usr/lib/python3/dist-packages/catfish_lib/Window.py", line 165, in __new__
    builder = get_builder(__builder__['ui_file'])
  File "/usr/lib/python3/dist-packages/catfish_lib/helpers.py", line 63, in get_builder
    builder.add_from_file(ui_filename)
  File "/usr/lib/python3/dist-packages/catfish_lib/Builder.py", line 81, in add_from_file
    Gtk.Builder.add_from_file(self, filename)
gi._glib.GError: /usr/share/catfish/ui/CatfishWindow.ui: required gtk+ version 3.12, current version is 3.10
Maybe a dependency not met?

I even added deb http://cz.archive.ubuntu.com/ubuntu xenial main universe to /etc/apt/$


Thank you in advance

**Comment by chrisbaldauf** [comment]
Hi @stepnjump,

I think you might have the wrong catfish project. This was a very short-lived Ruby project and the debugging output that you've posted lists catfish.py.
